apiVersion: aerjob.nav.io/v2
kind: QuantumAerJob
metadata:
  labels:
    app.kubernetes.io/name: quantum-job-operator
    app.kubernetes.io/managed-by: kustomize
  name: quantumaerjob-sample
spec:
  # TODO(user): Add fields here
