# This rule is not used by the project quantum-job-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the aerjob.nav.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: quantum-job-operator
    app.kubernetes.io/managed-by: kustomize
  name: quantumaerjob-editor-role
rules:
- apiGroups:
  - aerjob.nav.io
  resources:
  - quantumaerjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - aerjob.nav.io
  resources:
  - quantumaerjobs/status
  verbs:
  - get
